package com.sigecap.sigecapexamenbackend.util;

public interface BusinessMsgError {

    String ERROR_USUARIO_ROL = "EL USUARIO NO TIENE EL ROL ADECUADO";
    String ERROR_USUARIO_INACTIVO = "EL USUARIO SE ENCUENTRA INACTIVO";
    String ERROR_USUARIO_INCORRECTO = "EL USUARIO O CLAVE NO COINCIDE";

    //validacion de respuestas
    String ERROR_EXISTE_RESPUESTA_CORRECTA="YA EXISTE UNA RESPUESTA CORRECTA PARA LA PREGUNTA SELECCIONADA";
    String ERROR_SIN_RESPUESTA = "NO DEBERIA DE REGISTRAR UNA RESPUESTA PARA ESTE TIPO DE PREGUNTA";
    String ERROR_NO_NUMERICO = "LA RESPUESTA PARA ESTA PREGUNTA DEBE SER NUMERICA";
    String ERROR_VERDADERO_REPETIDO = "YA EXISTE UNA RESPUESTA VERDADERA PARA ESA PREGUNTA";
    String ERROR_FALSO_REPETIDO = "YA EXISTE UNA RESPUESTA FALSA PARA ESA PREGUNTA";

    String ERROR_NO_SE_ENCUENTRA_PARTICIPANTE_EXAMEN = "NO SE ENCUENTRA EL PARTICIPANTE INSCRITO EN EL EXAMEN";

}
