package com.sigecap.sigecapexamenbackend.util;

public interface BusinessMsgError {

    String ERROR_USUARIO_ROL = "EL USUARIO NO TIENE EL ROL ADECUADO";
    String ERROR_USUARIO_INACTIVO = "EL USUARIO SE ENCUENTRA INACTIVO";
    String ERROR_USUARIO_INCORRECTO = "EL USUARIO O CLAVE NO COINCIDE";

    //validacion de respuestas
    String ERROR_EXISTE_RESPUESTA_CORRECTA="YA EXISTE UNA RESPUESTA CORRECTA PARA LA PREGUNTA SELECCIONADA";
    String ERROR_SIN_RESPUESTA = "NO DEBERIA DE REGISTRAR UNA RESPUESTA PARA ESTE TIPO DE PREGUNTA";
    String ERROR_NO_NUMERICO = "LA RESPUESTA PARA ESTA PREGUNTA DEBE SER NUMERICA";
    String ERROR_VERDADERO_REPETIDO = "YA EXISTE UNA RESPUESTA VERDADERA PARA ESA PREGUNTA";
    String ERROR_FALSO_REPETIDO = "YA EXISTE UNA RESPUESTA FALSA PARA ESA PREGUNTA";

    String ERROR_NO_SE_ENCUENTRA_PARTICIPANTE_EXAMEN = "NO SE ENCUENTRA EL PARTICIPANTE INSCRITO EN EL EXAMEN";


    //validacion iniciar examen
    String ERROR_NO_REALIZO_ENCUESTA = "EL ALUMNO NO HA REALIZADO LA ENCUESTA";
    String ERROR_NO_REALIZO_ASISTENCIA = "EL ALUMNO NO HA REALIZADO LA ASISTENCIA";
    String ERROR_FECHA_INICIO_EXAMEN = "LA FECHA Y HORA DE INICIO DEL EXAMEN NO CORRESPONDE A LA FECHA Y HORA ACTUAL";
    String ERROR_FECHA_FIN_EXAMEN = "EL EXAMEN SE ENCUENTRA CERRADO O FINALIZADO";
    String ERROR_NUMEROS_INTENTOS_ = "YA UTILIZASTE LOS NUMEROS DE INTENTOS PERMITIDOS PARA EL EXAMEN";

}
